name: "campus_online"
description: "Z Kampüs information and navigation app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.4.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
flutter_native_splash:
  color: "#8B2232"
  color_dark: "#8B2232"
  android: true
  ios: true
  web: false # Web için açılış ekranını devre dışı bırakıyoruz

  # Android 12 ve sonrası için özel ayarlar
  android_12:
    color: "#8B2232"
    color_dark: "#8B2232"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/campus-online_new-logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/izu_fallback.jpg
